### ISSUE TITLE
[Vue warn]:

### ISSUE THREAD

**Issue by chendianwei** [Vanthink-UED/vue-core-image-upload#83]
Property or method "data" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option.

**Comment by Lucassssss** [comment]
遇到了同样的问题 @chendianwei 有解决掉吗？

**Comment by JackPu** [comment]
Can you paste your `.vue` file contents?

**Comment by BloodLuna** [comment]
follow the steps [http://vanthink-ued.github.io/vue-core-image-upload/index.html#/cn/get-started](url)
```
<template>
<div class="center">
  <vue-core-image-upload
    class="btn btn-primary"
    :crop="false"
    @imageuploaded="imageuploaded"
    :data="data"
    :max-file-size="5242880"
    url="http://101.198.151.190/api/upload.php" >
  </vue-core-image-upload>
</div>
</template>

<script>
import VueCoreImageUpload from 'vue-core-image-upload'

export default {
  components: {
    'vue-core-image-upload': VueCoreImageUpload,
  },
  data() {
    return {
      src: 'http://img1.vued.vanthink.cn/vued0a233185b6027244f9d43e653227439a.png',
    }
  },
  methods: {
    imageuploaded(res) {
      if (res.errcode == 0) {
        this.src = res.data.src;
      }
    }
  }
};
</script>
```
AND
```
vue.esm.js?65d7:476 [Vue warn]: Property or method "data" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option.

found in

---> <Create> at src\components\Create.vue
       <Index> at src\components\Index.vue
         <App> at src\App.vue
           <Root>
```

**Comment by BloodLuna** [comment]
also
```
vue.esm.js?65d7:102 Uncaught TypeError: Cannot read property 'toLowerCase' of undefined
    at eval (webpack-internal:///4:103:38)
    at Object.isReservedTag (webpack-internal:///4:4884:28)
    at Function.Vue.(anonymous function) [as component] (webpack-internal:///4:4543:46)
    at Object.install (webpack-internal:///221:6:11)
    at Function.Vue.use (webpack-internal:///4:4411:22)
    at eval (webpack-internal:///58:23:46)
    at Object.<anonymous> (http://127.0.0.1:8888/app.js:1080:1)
    at __webpack_require__ (http://127.0.0.1:8888/app.js:660:30)
    at fn (http://127.0.0.1:8888/app.js:86:20)
    at Object.<anonymous> (http://127.0.0.1:8888/app.js:1737:18)
```
